// 08-vue/bilibili/vue2_test/34_src_路由的params参数/pages/Message.vue
<template>
  <div>
    <ul>
      <li v-for="message in messageList" :key="message.id">
        <!-- 跳转路由并携带params参数，to的字符串写法 -->
        <!-- <router-link :to="`/home/message/detail/${m.id}/${m.title}`">{{message.title}}</router-link> -->

        <!-- 跳转路由并携带params参数，to的对象写法 -->
        <router-link
            :to="{
            name: 'detail',
            params: {
              id: message.id,
              title: message.title,
            },
          }"
        >
          {{ message.title }}
        </router-link>
      </li>
    </ul>
    <hr/>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Message",
  data() {
    return {
      messageList: [
        {id: "001", title: "消息001"},
        {id: "002", title: "消息002"},
        {id: "003", title: "消息003"},
      ],
    };
  },
};
</script>

<style scoped>
</style>

// 06-react/2-react-stagging/13-src-路由携带search参数/pages/Hmoe/Message/index.jsx
import React, {Component} from 'react';
import {Link, Routes, Route} from "react-router-dom";
import Detail from "./Detail";

class Message extends Component {
    state = {
        messageArr: [
            {id: '001', title: '消息1'},
            {id: '002', title: '消息2'},
            {id: '003', title: '消息3'},
        ]
    }

    render() {
        return (
            <div>
                <ul>
                    {
                        this.state.messageArr.map((msgObj) => {
                            return (
                                <li key={msgObj.id}>
                                    {/* 跳转路由时携带params参数 */}
                                    {/*<Link to={`/home/message/detail/${msgObj.id}/${msgObj.title}`}>{msgObj.title}</Link>&nbsp;&nbsp;*/}

                                    {/* 跳转路由时携带search参数 */}
                                    <Link
                                        to={`/home/message/detail?id=${msgObj.id}&title=${msgObj.title}`}>{msgObj.title}</Link>&nbsp;&nbsp;
                                </li>
                            )
                        })
                    }
                </ul>
                <hr/>
                <Routes>
                    {/* 注册路由时，声明接收params参数 */}
                    {/*<Route path="detail" element={<Detail/>}/>*/}
                    {/*<Route path="detail/:id/:title" element={<Detail/>}/>*/}

                    {/* 注册路由时，如果携带的是search参数，无需声明接收，直接注册即可 */}
                    <Route path="detail" element={<Detail/>}/>
                </Routes>
            </div>
        );
    }
}

export default Message;
