// 06-react/2-react-stagging/src/components/List/index.jsx
import React, {Component} from 'react';
import Item from "../Item";
import './index.css'

class List extends Component {
    render() {
        const {todos} = this.props
        return (
            <ul className="todo-main">
                {
                    todos.map((todoObj) => {
                        return <Item key={todoObj.id} {...todoObj}/>
                    })
                }
            </ul>
        );
    }
}

export default List;

// 08-vue/2_vue_components/4-src-todoList/components/List.vue
<template>
  <ul class="todo-main">
    <Item
        v-for="(todo,index) in todos"
        :key="todo.id"
        :todo="todo"
        :updateOne="updateOne"
        :index="index"
        :deleteOne="deleteOne"
    ></Item>
  </ul>
</template>

<script>
import Item from "./Item";

export default {
  name: "List",
  props: ['todos', 'updateOne', 'deleteOne'],
  components: {
    Item
  }
}
</script>

<style scoped>
/*main*/
.todo-main {
  margin-left: 0px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding: 0px;
}

.todo-empty {
  height: 40px;
  line-height: 40px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding-left: 5px;
  margin-top: 10px;
}
</style>
