// 06-react/2-react-stagging/2-src-todoList/components/Item/index.jsx
import React, {Component} from 'react';
import './index.css'

class Item extends Component {

    state = {
        mouseIn: false//标识鼠标是否在当前todo项中
    }

    //勾选or取消勾选一个todo的回调
    handleCheck = (id) => {
        return ({target}) => {
            // 调用App传递过来的checkTodo
            this.props.checkTodo(id, target.checked)
        }
    }

    //鼠标移入移出的回调
    handleMouse = (mouseIn) => {
        return () => {
            this.setState({mouseIn})
        }
    }

    // 删除按钮的问题
    handleDelete = (id) => {
        /* eslint-disable */
        if (confirm('确认删除吗？')) {
            this.props.deleteTodo(id)
        }
    }


    render() {
        const {id, name, done} = this.props
        const {mouseIn} = this.state
        return (
            <li onMouseEnter={this.handleMouse(true)} onMouseLeave={this.handleMouse(false)}
                style={{background: mouseIn ? '#ddd' : 'white'}}>
                <label>
                    <input type="checkbox" checked={done} onChange={this.handleCheck(id)}/>
                    <span>{name}</span>
                </label>
                <button className="btn btn-danger" onClick={() => {
                    this.handleDelete(id)
                }}
                        style={{display: mouseIn ? 'block' : 'none'}}>删除
                </button>
            </li>
        );
    }
}

export default Item;

// 08-vue/bilibili/vue2_test/13_src_TodoList全局事件总线/components/Item.vue
<template>
  <div>
    <li>
      <label>
        <input
            type="checkbox"
            :checked="todo.done"
            @click="handleCheck(todo.id)"
        />
        <!-- 如下代码也能实现功能，但是不太推荐，因为有点违反原则，因为修改了props -->
        <!-- <input type="checkbox" v-model="todo.done"/> -->
        <span>{{ todo.title }}</span>
      </label>
      <button class="btn btn-danger" @click="handleDelete(todo.id)">
        删除
      </button>
    </li>
  </div>
</template>

<script>
export default {
  name: "Item",
  props: ["todo"],
  methods: {
    // 勾选or取消勾选
    handleCheck(id) {
      // 通知App组件将对应的todo对象的done值取反
      this.$bus.$emit("checkTodo", id);
    },
    // 删除
    handleDelete(id) {
      if (confirm("确定删除吗？")) {
        // 通知App组件将对应的todo对象删除
        this.$bus.$emit("deleteTodo", id);
      }
    },
  },
};
</script>

<style scoped>
/*item*/
li {
  list-style: none;
  height: 36px;
  line-height: 36px;
  padding: 0 5px;
  border-bottom: 1px solid #ddd;
}

li label {
  float: left;
  cursor: pointer;
}

li label li input {
  vertical-align: middle;
  margin-right: 6px;
  position: relative;
  top: -1px;
}

li button {
  float: right;
  display: none;
  margin-top: 3px;
}

li:before {
  content: initial;
}

li:last-child {
  border-bottom: none;
}

li:hover {
  background-color: #ddd;
}

li:hover button {
  display: block;
}
</style>
