// 06-react/3-redux/src/containers/Person/index.jsx
import React, {Component} from 'react';
import {connect} from "react-redux";
import {createAddPersonAction} from "../../redux/actions/person";

class Person extends Component {

    add = () => {
        const {nameNode, ageNode} = this
        console.log(nameNode.value, ageNode.value)
        this.props.jiaYiRen({id: Date.now(), name: nameNode.value, age: ageNode.value})
    }

    render() {
        return (
            <div>
                <h3>我是Person组件,上方组件求和为:{this.props.sum}</h3>
                <input ref={c => this.nameNode = c} type="text" placeholder="输入名字"/>
                <input ref={c => this.ageNode = c} type="text" placeholder="输入年龄"/>
                <button onClick={this.add}>添加</button>
                <ul>
                    {
                        this.props.rens.map((personObj) => {
                            return <li key={personObj.id}> {personObj.name}----{personObj.age}</li>
                        })
                    }
                </ul>
            </div>
        );
    }
}

export default connect(
    state => ({
        rens: state.yiduiren,
        sum: state.sum
    }),
    {
        jiaYiRen: createAddPersonAction
    }
)(Person)

// 08-vue/bilibili/vue2_test/28_src_求和案例_多组件共享数据/components/Person.vue
<template>
  <div>
    <h1>人员列表</h1>
    <h3 style="color: red">Count组件求和为：{{ sum }}</h3>
    <input type="text" placeholder="请输入名字" v-model="name"/>
    <button @click="add">添加</button>
    <ul>
      <li v-for="person in personList" :key="person.id">{{ person.name }}</li>
    </ul>
  </div>
</template>

<script>
import {nanoid} from "nanoid";

export default {
  name: "Person",
  data() {
    return {
      name: "",
    };
  },
  computed: {
    personList() {
      return this.$store.state.personList;
    },
    sum() {
      return this.$store.state.sum;
    },
  },
  methods: {
    add() {
      const personObj = {id: nanoid(), name: this.name};
      this.$store.commit("ADD_PERSON", personObj);
      this.name = "";
    },
  },
};
</script>

<style scoped>
</style>
